<?php
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function halloween_lunch_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'lunch_order_form') {

    // Change the title of fullname field
    $form['fullname']['#title'] = t('Your Name');

    // Unset textarea field
    unset($form['instructions']);

    // Enable AJAX on delivery date field
    $form['delivery_date']['#ajax'] = [
      'callback' => 'halloween_lunch_delivery_date_callback',
      'wrapper' => 'menu-choices-wrapper'
    ];

    // Add <div> wrapper to menu choices field
    $form['menu_choices']['#prefix'] = '<div id="menu-choices-wrapper">';
    $form['menu_choices']['#suffix'] = '</div>';

    // If date is Halloween, then add an additional menu option
    if ($form_state->getValue('delivery_date') == '2016-10-31') {
      $form['menu_choices']['#options'][] = t('Pumpkin Pie');
    }

  }
}

function halloween_lunch_delivery_date_callback(array $form, FormStateInterface $form_state) {
  return $form['menu_choices'];
}